//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A criterion specifying the characteristics that a person should or should not meet or have in order 
 * 				to be eligible to participate in the clinical study.
 * 				A criterion can be either inclusion or exclusion depending on the List in which the criterion 
 * 				belongs to.
 * 				A criterion may refer to the age, sex, type and stage of disease, previous treatment history, and other 
 * 				medical conditions of a person (or any proper combination of the above), among others.
 * 				A criterion in order to be properly defined apart from its attributes such as a unique identifier,
 * 				it should also have a human readable description (Description element) and zero or more formal 
 * 				representations of the criterion (FormalExpression element) in the languages of our choice.
 * 			
 * 
 * <p>Java class for criterion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="criterion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ntua.org/criteria}criterionAttributes">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FormalExpression" type="{http://www.ntua.org/criteria}formalExpression" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "criterion", propOrder = {
    "description",
    "formalExpression"
})
public class Criterion
    extends CriterionAttributes
{

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "FormalExpression")
    protected List<FormalExpression> formalExpression;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the formalExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formalExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormalExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormalExpression }
     * 
     * 
     */
    public List<FormalExpression> getFormalExpression() {
        if (formalExpression == null) {
            formalExpression = new ArrayList<FormalExpression>();
        }
        return this.formalExpression;
    }

}
