//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for criterionUsageStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="criterionUsageStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="USED"/>
 *     &lt;enumeration value="PARTIALLY-USED"/>
 *     &lt;enumeration value="NOT-USED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "criterionUsageStatus")
@XmlEnum
public enum CriterionUsageStatus {

    USED("USED"),
    @XmlEnumValue("PARTIALLY-USED")
    PARTIALLY_USED("PARTIALLY-USED"),
    @XmlEnumValue("NOT-USED")
    NOT_USED("NOT-USED");
    private final String value;

    CriterionUsageStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CriterionUsageStatus fromValue(String v) {
        for (CriterionUsageStatus c: CriterionUsageStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
