//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formalExpressionContent.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="formalExpressionContent">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HarmonicSS_ReferenceXSD"/>
 *     &lt;enumeration value="HarmonicSS_ReferenceModel"/>
 *     &lt;enumeration value="HarmonicSS_ReferenceOntology"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "formalExpressionContent")
@XmlEnum
public enum FormalExpressionContent {

    @XmlEnumValue("HarmonicSS_ReferenceXSD")
    HARMONIC_SS_REFERENCE_XSD("HarmonicSS_ReferenceXSD"),
    @XmlEnumValue("HarmonicSS_ReferenceModel")
    HARMONIC_SS_REFERENCE_MODEL("HarmonicSS_ReferenceModel"),
    @XmlEnumValue("HarmonicSS_ReferenceOntology")
    HARMONIC_SS_REFERENCE_ONTOLOGY("HarmonicSS_ReferenceOntology");
    private final String value;

    FormalExpressionContent(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormalExpressionContent fromValue(String v) {
        for (FormalExpressionContent c: FormalExpressionContent.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
