//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				In the response we should provide
 * 				a) The Number of Eligible Patients Detected for each Cohort
 * 				b) The Eligibility Criteria Used 
 * 				In case of Patients IDs request, we should additionally provide 
 * 				c) The IDs of Eligible patients for each Cohort
 * 			
 * 
 * <p>Java class for patientsSelectionResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patientsSelectionResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ntua.org/criteria}responseAttributes">
 *       &lt;sequence>
 *         &lt;element name="CohortResponse" type="{http://www.ntua.org/criteria}cohortResponse" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patientsSelectionResponse", propOrder = {
    "cohortResponse"
})
public class PatientsSelectionResponse
    extends ResponseAttributes
{

    @XmlElement(name = "CohortResponse", required = true)
    protected List<CohortResponse> cohortResponse;

    /**
     * Gets the value of the cohortResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohortResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohortResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CohortResponse }
     * 
     * 
     */
    public List<CohortResponse> getCohortResponse() {
        if (cohortResponse == null) {
            cohortResponse = new ArrayList<CohortResponse>();
        }
        return this.cohortResponse;
    }

}
