//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				For each request we should specify:
 * 				a) the Unique ID of the user 
 * 				b) the Patient Data we are looking for
 * 				c) the Eligibility Criteria that the patients should satisfy
 * 				d) the Unique ID of the Cohorts in which the search process will take place
 * 				Additionally, we should specify:
 * 				i) a unique ID (session ID)
 * 				ii) the date when the request initiated
 * 			
 * 
 * <p>Java class for patientsSelectionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patientsSelectionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ntua.org/criteria}requestAttributes">
 *       &lt;sequence>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestID" type="{http://www.ntua.org/criteria}patientSelectionType"/>
 *         &lt;element name="EligibilityCriteria" type="{http://www.ntua.org/criteria}eligibilityCriteria"/>
 *         &lt;element name="CohortID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patientsSelectionRequest", propOrder = {
    "userID",
    "requestTitle",
    "requestID",
    "eligibilityCriteria",
    "cohortID"
})
public class PatientsSelectionRequest
    extends RequestAttributes
{

    @XmlElement(name = "UserID", required = true)
    protected String userID;
    @XmlElement(name = "RequestTitle", required = true)
    protected String requestTitle;
    @XmlElement(name = "RequestID", required = true)
    @XmlSchemaType(name = "string")
    protected PatientSelectionType requestID;
    @XmlElement(name = "EligibilityCriteria", required = true)
    protected EligibilityCriteria eligibilityCriteria;
    @XmlElement(name = "CohortID", required = true)
    protected List<String> cohortID;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the requestTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestTitle() {
        return requestTitle;
    }

    /**
     * Sets the value of the requestTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestTitle(String value) {
        this.requestTitle = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link PatientSelectionType }
     *     
     */
    public PatientSelectionType getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientSelectionType }
     *     
     */
    public void setRequestID(PatientSelectionType value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the eligibilityCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityCriteria }
     *     
     */
    public EligibilityCriteria getEligibilityCriteria() {
        return eligibilityCriteria;
    }

    /**
     * Sets the value of the eligibilityCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityCriteria }
     *     
     */
    public void setEligibilityCriteria(EligibilityCriteria value) {
        this.eligibilityCriteria = value;
    }

    /**
     * Gets the value of the cohortID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohortID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohortID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCohortID() {
        if (cohortID == null) {
            cohortID = new ArrayList<String>();
        }
        return this.cohortID;
    }

}
