//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Concerning the response retrieved from each cohort, we should provide 
 * 				the date when the Cohort queried along with the number or eligible patients found, 
 * 				the IDs of eligible patients (in case of Patients' IDs Request) and
 * 				the eligibility criteria used in the search process in the specific Cohort.
 * 			
 * 
 * <p>Java class for cohortResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cohortResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ntua.org/criteria}cohortResponseAttributes">
 *       &lt;sequence>
 *         &lt;element name="EligiblePatientsNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EligiblePatientsIDs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EligibilityCriteriaUsed" type="{http://www.ntua.org/criteria}eligibilityCriteriaUsed"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cohortResponse", propOrder = {
    "eligiblePatientsNumber",
    "eligiblePatientsIDs",
    "eligibilityCriteriaUsed"
})
public class CohortResponse
    extends CohortResponseAttributes
{

    @XmlElement(name = "EligiblePatientsNumber")
    protected int eligiblePatientsNumber;
    @XmlElement(name = "EligiblePatientsIDs")
    protected String eligiblePatientsIDs;
    @XmlElement(name = "EligibilityCriteriaUsed", required = true)
    protected EligibilityCriteriaUsed eligibilityCriteriaUsed;

    /**
     * Gets the value of the eligiblePatientsNumber property.
     * 
     */
    public int getEligiblePatientsNumber() {
        return eligiblePatientsNumber;
    }

    /**
     * Sets the value of the eligiblePatientsNumber property.
     * 
     */
    public void setEligiblePatientsNumber(int value) {
        this.eligiblePatientsNumber = value;
    }

    /**
     * Gets the value of the eligiblePatientsIDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligiblePatientsIDs() {
        return eligiblePatientsIDs;
    }

    /**
     * Sets the value of the eligiblePatientsIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligiblePatientsIDs(String value) {
        this.eligiblePatientsIDs = value;
    }

    /**
     * Gets the value of the eligibilityCriteriaUsed property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityCriteriaUsed }
     *     
     */
    public EligibilityCriteriaUsed getEligibilityCriteriaUsed() {
        return eligibilityCriteriaUsed;
    }

    /**
     * Sets the value of the eligibilityCriteriaUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityCriteriaUsed }
     *     
     */
    public void setEligibilityCriteriaUsed(EligibilityCriteriaUsed value) {
        this.eligibilityCriteriaUsed = value;
    }

}
