//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				For a criterion we should mentioned whether it has been used 
 * 				in the search process or not (partially used or not used).
 * 				In any case we can provide additional information such as 
 * 				the reason for which a criterion has been partially used, 
 * 				or not used at all. 
 * 			
 * 
 * <p>Java class for criterionUsage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="criterionUsage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ntua.org/criteria}criterionUsageAttributes">
 *       &lt;sequence>
 *         &lt;element name="NotesJSON" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NotesHTML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "criterionUsage", propOrder = {
    "notesJSON",
    "notesHTML"
})
public class CriterionUsage
    extends CriterionUsageAttributes
{

    @XmlElement(name = "NotesJSON")
    protected String notesJSON;
    @XmlElement(name = "NotesHTML")
    protected String notesHTML;

    /**
     * Gets the value of the notesJSON property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotesJSON() {
        return notesJSON;
    }

    /**
     * Sets the value of the notesJSON property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotesJSON(String value) {
        this.notesJSON = value;
    }

    /**
     * Gets the value of the notesHTML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotesHTML() {
        return notesHTML;
    }

    /**
     * Sets the value of the notesHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotesHTML(String value) {
        this.notesHTML = value;
    }

}
