//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for criterionUsageAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="criterionUsageAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="criterionID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="criterionUsageStatus" use="required" type="{http://www.ntua.org/criteria}criterionUsageStatus" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "criterionUsageAttributes")
@XmlSeeAlso({
    CriterionUsage.class
})
public class CriterionUsageAttributes {

    @XmlAttribute(name = "criterionID", required = true)
    protected String criterionID;
    @XmlAttribute(name = "criterionUsageStatus", required = true)
    protected CriterionUsageStatus criterionUsageStatus;

    /**
     * Gets the value of the criterionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCriterionID() {
        return criterionID;
    }

    /**
     * Sets the value of the criterionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCriterionID(String value) {
        this.criterionID = value;
    }

    /**
     * Gets the value of the criterionUsageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CriterionUsageStatus }
     *     
     */
    public CriterionUsageStatus getCriterionUsageStatus() {
        return criterionUsageStatus;
    }

    /**
     * Sets the value of the criterionUsageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriterionUsageStatus }
     *     
     */
    public void setCriterionUsageStatus(CriterionUsageStatus value) {
        this.criterionUsageStatus = value;
    }

}
