//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A Formal Expression can be expressed in any machine processable language including SPARQL, JSON and XML.
 * 				The only restriction is the expression provided to be evaluated to True or False.
 * 			
 * 
 * <p>Java class for formalExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formalExpression">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ntua.org/criteria}formalExpressionAttributes">
 *       &lt;choice>
 *         &lt;element name="BooleanExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formalExpression", propOrder = {
    "booleanExpression",
    "notes"
})
public class FormalExpression
    extends FormalExpressionAttributes
{

    @XmlElement(name = "BooleanExpression")
    protected String booleanExpression;
    @XmlElement(name = "Notes")
    protected String notes;

    /**
     * Gets the value of the booleanExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBooleanExpression() {
        return booleanExpression;
    }

    /**
     * Sets the value of the booleanExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBooleanExpression(String value) {
        this.booleanExpression = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
