//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for module.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="module">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HarmonicSS_GUI"/>
 *     &lt;enumeration value="HarmonicSS_PatientSelection"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "module")
@XmlEnum
public enum Module {

    @XmlEnumValue("HarmonicSS_GUI")
    HARMONIC_SS_GUI("HarmonicSS_GUI"),
    @XmlEnumValue("HarmonicSS_PatientSelection")
    HARMONIC_SS_PATIENT_SELECTION("HarmonicSS_PatientSelection");
    private final String value;

    Module(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Module fromValue(String v) {
        for (Module c: Module.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
