//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 01:56:31 PM EET 
//


package org.ntua.criteria;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ntua.criteria package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PatientsSelectionResponse_QNAME = new QName("http://www.ntua.org/criteria", "PatientsSelectionResponse");
    private final static QName _PatientsSelectionRequest_QNAME = new QName("http://www.ntua.org/criteria", "PatientsSelectionRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ntua.criteria
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatientsSelectionResponse }
     * 
     */
    public PatientsSelectionResponse createPatientsSelectionResponse() {
        return new PatientsSelectionResponse();
    }

    /**
     * Create an instance of {@link PatientsSelectionRequest }
     * 
     */
    public PatientsSelectionRequest createPatientsSelectionRequest() {
        return new PatientsSelectionRequest();
    }

    /**
     * Create an instance of {@link FormalExpression }
     * 
     */
    public FormalExpression createFormalExpression() {
        return new FormalExpression();
    }

    /**
     * Create an instance of {@link RequestAttributes }
     * 
     */
    public RequestAttributes createRequestAttributes() {
        return new RequestAttributes();
    }

    /**
     * Create an instance of {@link Criterion }
     * 
     */
    public Criterion createCriterion() {
        return new Criterion();
    }

    /**
     * Create an instance of {@link CriterionAttributes }
     * 
     */
    public CriterionAttributes createCriterionAttributes() {
        return new CriterionAttributes();
    }

    /**
     * Create an instance of {@link ResponseAttributes }
     * 
     */
    public ResponseAttributes createResponseAttributes() {
        return new ResponseAttributes();
    }

    /**
     * Create an instance of {@link CriterionUsageAttributes }
     * 
     */
    public CriterionUsageAttributes createCriterionUsageAttributes() {
        return new CriterionUsageAttributes();
    }

    /**
     * Create an instance of {@link CohortResponse }
     * 
     */
    public CohortResponse createCohortResponse() {
        return new CohortResponse();
    }

    /**
     * Create an instance of {@link CohortResponseAttributes }
     * 
     */
    public CohortResponseAttributes createCohortResponseAttributes() {
        return new CohortResponseAttributes();
    }

    /**
     * Create an instance of {@link CriteriaList }
     * 
     */
    public CriteriaList createCriteriaList() {
        return new CriteriaList();
    }

    /**
     * Create an instance of {@link CriterionUsage }
     * 
     */
    public CriterionUsage createCriterionUsage() {
        return new CriterionUsage();
    }

    /**
     * Create an instance of {@link FormalExpressionAttributes }
     * 
     */
    public FormalExpressionAttributes createFormalExpressionAttributes() {
        return new FormalExpressionAttributes();
    }

    /**
     * Create an instance of {@link EligibilityCriteria }
     * 
     */
    public EligibilityCriteria createEligibilityCriteria() {
        return new EligibilityCriteria();
    }

    /**
     * Create an instance of {@link EligibilityCriteriaUsed }
     * 
     */
    public EligibilityCriteriaUsed createEligibilityCriteriaUsed() {
        return new EligibilityCriteriaUsed();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientsSelectionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ntua.org/criteria", name = "PatientsSelectionResponse")
    public JAXBElement<PatientsSelectionResponse> createPatientsSelectionResponse(PatientsSelectionResponse value) {
        return new JAXBElement<PatientsSelectionResponse>(_PatientsSelectionResponse_QNAME, PatientsSelectionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientsSelectionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ntua.org/criteria", name = "PatientsSelectionRequest")
    public JAXBElement<PatientsSelectionRequest> createPatientsSelectionRequest(PatientsSelectionRequest value) {
        return new JAXBElement<PatientsSelectionRequest>(_PatientsSelectionRequest_QNAME, PatientsSelectionRequest.class, null, value);
    }

}
